### ISSUE TITLE
Missing Folder and file 

### ISSUE THREAD

**Issue by Peral38** [crowdsecurity/cs-standalone-php-bouncer#7]
The folder vendor is missing and  the file autoload.php too

**Comment by AlteredCoder** [comment]
Hello, i think those files are missing because the `composer install` command failed.
Can you try to run `composer install` to see what happen ?

**Comment by Peral38** [comment]
Hello,
No problem for me with composer installation : 

pi@Canna-pi:~/Downloads $ HASH=`curl -sS https://composer.github.io/installer.sig`
pi@Canna-pi:~/Downloads $ php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
Installer verified


pi@Canna-pi:~/Downloads $ sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
All settings correct for using Composer
Downloading...

Composer (version 2.2.7) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

**Comment by Peral38** [comment]
So i check the installation script and tryed to run manually the composer command and i got this : 

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - gregwar/captcha is locked to version v1.1.9 and an update of this package was not requested.
    - gregwar/captcha v1.1.9 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - gregwar/captcha v1.1.9 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - crowdsec/bouncer v0.13.2 requires gregwar/captcha ^1.1 -> satisfiable by gregwar/captcha[v1.1.9].
    - crowdsec/bouncer is locked to version v0.13.2 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.3/cli/php.ini
    - /etc/php/7.3/cli/conf.d/10-opcache.ini
    - /etc/php/7.3/cli/conf.d/10-pdo.ini
    - /etc/php/7.3/cli/conf.d/20-calendar.ini
    - /etc/php/7.3/cli/conf.d/20-ctype.ini
    - /etc/php/7.3/cli/conf.d/20-exif.ini
    - /etc/php/7.3/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.3/cli/conf.d/20-ftp.ini
    - /etc/php/7.3/cli/conf.d/20-gettext.ini
    - /etc/php/7.3/cli/conf.d/20-iconv.ini
    - /etc/php/7.3/cli/conf.d/20-json.ini
    - /etc/php/7.3/cli/conf.d/20-phar.ini
    - /etc/php/7.3/cli/conf.d/20-posix.ini
    - /etc/php/7.3/cli/conf.d/20-readline.ini
    - /etc/php/7.3/cli/conf.d/20-shmop.ini
    - /etc/php/7.3/cli/conf.d/20-sockets.ini
    - /etc/php/7.3/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.3/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.3/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.3/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd --ignore-platform-req=ext-gd` to temporarily ignore these required extensions.
```
I installe that with : 
```
sudo apt-get install php7.3-gd
#check if installed
php -m | grep gd
#restart your web server 
sudo service apache2 restart
```


Now i try again to run composer install : 

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - gregwar/captcha is locked to version v1.1.9 and an update of this package was not requested.
    - gregwar/captcha v1.1.9 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 2
    - gregwar/captcha v1.1.9 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
    - crowdsec/bouncer v0.13.2 requires gregwar/captcha ^1.1 -> satisfiable by gregwar/captcha[v1.1.9].
    - crowdsec/bouncer is locked to version v0.13.2 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.3/cli/php.ini
    - /etc/php/7.3/cli/conf.d/10-opcache.ini
    - /etc/php/7.3/cli/conf.d/10-pdo.ini
    - /etc/php/7.3/cli/conf.d/20-calendar.ini
    - /etc/php/7.3/cli/conf.d/20-ctype.ini
    - /etc/php/7.3/cli/conf.d/20-exif.ini
    - /etc/php/7.3/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.3/cli/conf.d/20-ftp.ini
    - /etc/php/7.3/cli/conf.d/20-gd.ini
    - /etc/php/7.3/cli/conf.d/20-gettext.ini
    - /etc/php/7.3/cli/conf.d/20-iconv.ini
    - /etc/php/7.3/cli/conf.d/20-json.ini
    - /etc/php/7.3/cli/conf.d/20-phar.ini
    - /etc/php/7.3/cli/conf.d/20-posix.ini
    - /etc/php/7.3/cli/conf.d/20-readline.ini
    - /etc/php/7.3/cli/conf.d/20-shmop.ini
    - /etc/php/7.3/cli/conf.d/20-sockets.ini
    - /etc/php/7.3/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.3/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.3/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.3/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-mbstring --ignore-platform-req=ext-mbstring` to temporarily ignore these required extensions.

```

Then running again composer and found again another missing module : 

```
pi@Canna-pi:~/Downloads/cs-php-bouncer $ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - gregwar/captcha is locked to version v1.1.9 and an update of this package was not requested.
    - gregwar/captcha v1.1.9 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 2
    - gregwar/captcha v1.1.9 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
    - crowdsec/bouncer v0.13.2 requires gregwar/captcha ^1.1 -> satisfiable by gregwar/captcha[v1.1.9].
    - crowdsec/bouncer is locked to version v0.13.2 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.3/cli/php.ini
    - /etc/php/7.3/cli/conf.d/10-opcache.ini
    - /etc/php/7.3/cli/conf.d/10-pdo.ini
    - /etc/php/7.3/cli/conf.d/20-calendar.ini
    - /etc/php/7.3/cli/conf.d/20-ctype.ini
    - /etc/php/7.3/cli/conf.d/20-exif.ini
    - /etc/php/7.3/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.3/cli/conf.d/20-ftp.ini
    - /etc/php/7.3/cli/conf.d/20-gd.ini
    - /etc/php/7.3/cli/conf.d/20-gettext.ini
    - /etc/php/7.3/cli/conf.d/20-iconv.ini
    - /etc/php/7.3/cli/conf.d/20-json.ini
    - /etc/php/7.3/cli/conf.d/20-phar.ini
    - /etc/php/7.3/cli/conf.d/20-posix.ini
    - /etc/php/7.3/cli/conf.d/20-readline.ini
    - /etc/php/7.3/cli/conf.d/20-shmop.ini
    - /etc/php/7.3/cli/conf.d/20-sockets.ini
    - /etc/php/7.3/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.3/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.3/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.3/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-mbstring --ignore-platform-req=ext-mbstring` to temporarily ignore these required extensions.
pi@Canna-pi:~/Downloads/cs-php-bouncer $ sudo apt-get install php7.3-mbstring
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  libnet-ssleay-perl libpng12-0 libwhisker2-perl perl-openssl-defaults python-colorzero
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
Les NOUVEAUX paquets suivants seront installés :
  php7.3-mbstring
0 mis à jour, 1 nouvellement installés, 0 à enlever et 132 non mis à jour.
Il est nécessaire de prendre 472 ko dans les archives.
Après cette opération, 1 485 ko d'espace disque supplémentaires seront utilisés.
Réception de :1 http://mirrors.ircam.fr/pub/raspbian/raspbian buster/main armhf php7.3-mbstring armhf 7.3.31-1~deb10u1 [472 kB]
472 ko réceptionnés en 0s (1 310 ko/s)
Sélection du paquet php7.3-mbstring précédemment désélectionné.
(Lecture de la base de données... 108936 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../php7.3-mbstring_7.3.31-1~deb10u1_armhf.deb ...
Dépaquetage de php7.3-mbstring (7.3.31-1~deb10u1) ...
Paramétrage de php7.3-mbstring (7.3.31-1~deb10u1) ...

Creating config file /etc/php/7.3/mods-available/mbstring.ini with new version
Traitement des actions différées (« triggers ») pour libapache2-mod-php7.3 (7.3.31-1~deb10u1) ...
pi@Canna-pi:~/Downloads/cs-php-bouncer $ sudo service apache2 restart
```


Then testing again and got a big error but i solved it but downloading again cs-php-bouncer

```
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 19 installs, 0 updates, 0 removals


  [RuntimeException]
  /home/pi/Downloads/cs-php-bouncer/vendor does not exist and could not be created.


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

pi@Canna-pi:~/Downloads/cs-php-bouncer $ cd ..
pi@Canna-pi:~/Downloads $ mkdir cs-php-bouncer-bis
pi@Canna-pi:~/Downloads $ cd cs-php-bouncer-bis/
pi@Canna-pi:~/Downloads/cs-php-bouncer-bis $ git clone https://github.com/crowdsecurity/cs-php-bouncer.git
Clonage dans 'cs-php-bouncer'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 51 (delta 21), reused 30 (delta 8), pack-reused 0
Dépaquetage des objets: 100% (51/51), fait.
pi@Canna-pi:~/Downloads/cs-php-bouncer-bis $ cd cs-php-bouncer/
pi@Canna-pi:~/Downloads/cs-php-bouncer-bis/cs-php-bouncer $ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 19 installs, 0 updates, 0 removals
  - Downloading symfony/polyfill-php81 (v1.23.0)
  - Downloading symfony/polyfill-php80 (v1.23.1)
  - Downloading symfony/polyfill-ctype (v1.23.0)
  - Downloading symfony/filesystem (v5.3.4)
  - Downloading symfony/deprecation-contracts (v2.4.0)
  - Downloading symfony/config (v5.3.4)
  - Downloading symfony/var-exporter (v5.3.7)
  - Downloading psr/container (1.1.1)
  - Downloading symfony/service-contracts (v2.4.0)
  - Downloading symfony/polyfill-php73 (v1.23.0)
  - Downloading psr/cache (1.0.1)
  - Downloading symfony/cache-contracts (v2.4.0)
  - Downloading psr/log (1.1.4)
  - Downloading symfony/cache (v5.3.7)
  - Downloading monolog/monolog (2.3.4)
  - Downloading mlocati/ip-lib (1.17.0)
  - Downloading symfony/finder (v5.3.7)
  - Downloading gregwar/captcha (v1.1.9)
  - Downloading crowdsec/bouncer (v0.13.2)
  - Installing symfony/polyfill-php81 (v1.23.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive
  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
  - Installing symfony/filesystem (v5.3.4): Extracting archive
  - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive
  - Installing symfony/config (v5.3.4): Extracting archive
  - Installing symfony/var-exporter (v5.3.7): Extracting archive
  - Installing psr/container (1.1.1): Extracting archive
  - Installing symfony/service-contracts (v2.4.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing symfony/cache-contracts (v2.4.0): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing symfony/cache (v5.3.7): Extracting archive
  - Installing monolog/monolog (2.3.4): Extracting archive
  - Installing mlocati/ip-lib (1.17.0): Extracting archive
  - Installing symfony/finder (v5.3.7): Extracting archive
  - Installing gregwar/captcha (v1.1.9): Extracting archive
  - Installing crowdsec/bouncer (v0.13.2): Extracting archive
Generating autoload files
14 packages you are using are looking for funding.
Use the `composer fund` command to find out more!


```
I deleting all and reinstall again to be sure but but now i still can't access to my php file when the bouncer is working,
I get this error in my apache error log : 
`[Wed Mar 16 00:47:37.940399 2022] [php7:error] [pid 4151] [client XXX.XXX.XX.XXX:30768] PHP Fatal error:  Uncaught Error: Class 'CrowdSecBouncer\\Exception' not found in /usr/local/php/crowdsec/vendor/crowdsec/bouncer/src/StandAloneBounce.php:123\nStack trace:\n#0 /usr/local/php/crowdsec/vendor/crowdsec/bouncer/src/AbstractBounce.php(108): CrowdSecBouncer\\StandAloneBounce->getBouncerInstance()\n#1 /usr/local/php/crowdsec/vendor/crowdsec/bouncer/src/AbstractBounce.php(54): CrowdSecBouncer\\AbstractBounce->bounceCurrentIp()\n#2 /usr/local/php/crowdsec/vendor/crowdsec/bouncer/src/StandAloneBounce.php(360): CrowdSecBouncer\\AbstractBounce->run()\n#3 /usr/local/php/crowdsec/crowdsec-php-bouncer.php(12): CrowdSecBouncer\\StandAloneBounce->safelyBounce()\n#4 {main}\n  thrown in /usr/local/php/crowdsec/vendor/crowdsec/bouncer/src/StandAloneBounce.php on line 123

`

**Comment by Peral38** [comment]
Should i open a new issue for the new error and close this one ?

**Comment by buixor** [comment]
Hello @Peral38 

Thanks for the issue, we're revamping a bit the bouncer because the user experience should be improved especially when things do not work as expected.
I'll keep you posted on this issue :+1:

**Comment by julienloizelet** [comment]
Closing because the new version 1.0.0 is a total redesign.
Thanks
